package com.careflow.common.enums;

public enum AuditAction {
    PATIENT_CREATED,
    PATIENT_UPDATED,
    PATIENT_DELETED,
    MEDICATION_ADDED,
    MEDICATION_UPDATED,
    MEDICATION_DISCONTINUED,
    CARE_PLAN_CREATED,
    CARE_PLAN_UPDATED,
    PATIENT_DISCHARGED,
    FOLLOW_UP_CREATED,
    FOLLOW_UP_COMPLETED,
    FOLLOW_UP_MISSED,
    RESPONSE_RECEIVED,
    RISK_SIGNAL_CREATED,
    ESCALATION_CREATED,
    ESCALATION_UPDATED,
    ESCALATION_ASSIGNED,
    ESCALATION_IN_REVIEW,
    ESCALATION_RESOLVED
}
